function(add_sanitizer_options TARGET)
  string(TOUPPER ${TARGET} UPPER_TARGET)
  option(ENABLE_ASAN_FOR_${UPPER_TARGET} "enable asan for ${TARGET}" ON)
  option(ENABLE_TSAN_FOR_${UPPER_TARGET} "enable tsan for ${TARGET}" OFF)
  if(ENABLE_ASAN_FOR_${UPPER_TARGET} AND ENABLE_TSAN_FOR_${UPPER_TARGET})
    message(SEND_ERROR "tsan and asan are mutually exclusive")
  endif()
  if(ENABLE_ASAN_FOR_${UPPER_TARGET})
      target_link_libraries(${TARGET} PRIVATE -fsanitize=address,undefined)
      target_compile_options(${TARGET} PRIVATE -fsanitize=address,undefined)
  endif()
  if(ENABLE_TSAN_FOR_${UPPER_TARGET})
      target_link_libraries(${TARGET} PRIVATE -fsanitize=thread)
      target_compile_options(${TARGET} PRIVATE -fsanitize=thread)
  endif()
endfunction()
